### ISSUE TITLE
ImportError: cannot import name MapperExtension

### ISSUE THREAD

**Issue by TYRANISTAR** [brentp/cruzdb#31]
Hello, 

Since there are many problems with cruzdb and Python 3 I decided to create a conda environment for python 2.7 and try there:

```
conda create --name py27 python=2.7
conda activate py27
pip install cruzdb
pip install SQLAlchemy 
pip install Flask-SQLAlchemy
#to avoid another error that appeared missing sqlalchemy
python
```

However when I try (in python):

`from cruzdb import Genome
`
I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/envs/py27/lib/python2.7/site-packages/cruzdb/__init__.py", line 5, in <module>
    from . import soup
  File "/home/user/anaconda3/envs/py27/lib/python2.7/site-packages/cruzdb/soup.py", line 1, in <module>
    from . import sqlsoup
  File "/home/user/anaconda3/envs/py27/lib/python2.7/site-packages/cruzdb/sqlsoup.py", line 11, in <module>
    from sqlalchemy.orm.interfaces import MapperExtension, EXT_CONTINUE
ImportError: cannot import name MapperExtension
```

Any thoughts?

**Comment by brentp** [comment]
Hi, thanks for giving it a try. I would try pinning to a version of sqlalchemy that's about 2 years old and see if that works.

**Comment by TYRANISTAR** [comment]
> Hi, thanks for giving it a try. I would try pinning to a version of sqlalchemy that's about 2 years old and see if that works.

Thanks for the answer. I uninstalled sqlalchemy and installed version 1.2.19

```
pip uninstall SQLAlchemy
pip uninstall Flask-SQLAlchemy
pip install SQLAlchemy==1.2.19
python
```
Then I tried again to import Genome and it worked!

Cheers!
